# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Maintain dependencies for Yarn
  - package-ecosystem: "yarn" 
    directory: "/" # Location of package manifests
    schedule:
       interval: "weekly"
    # Raise pull requests for version updates
    # to yarn against the `main` branch
       day: "sunday"
    target-branch: "main"
    # Labels on pull requests for version updates only
    labels:
      - "yarn dependencies"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. 
    # (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
     # Check for github-actions updates on Mon, Wed, and Fri
     day: [ "monday", "wednesday", "friday" ]
   # Labels on pull requests for security and version updates
   labels:
      - "github-actions"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
       - "npm dependencies"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
       - "composer dependencies"
